#     rename this to "settings.yaml" and fill in the values
debug: false
snmpv1_community: public
SuppressSnmpErrors: true #keep true. 
debug_date: false
debug_MM_YYYY: 9-2001 
DateFilenameOffset: -5 #if x days before the 1st, date it for next month
subnets: #for findpriners.sh - subnets to search for priners in. will be used if debug is false.
 - 10.0.0.0/24
 - 192.168.1.0/24
knownprinters: #if debug is false this is ignored
  - 10.1.1.2
  - 10.1.1.3
  - 10.1.2.3
  - 192.168.1.1 
multithreading: true #not possible right now
max_threads: 8 
#PrinterTest: #not for the csv - what to test to see if it's a printer 
#  - .1.3.6.1.2.1.43.11.1.1.9.1  # Toner C
#  - .1.3.6.1.2.1.43.11.1.1.9.2  # Toner Y
#  - .1.3.6.1.2.1.43.11.1.1.9.3  # Toner M
#  - .1.3.6.1.2.1.43.11.1.1.9.4  # Toner K
#  - .1.3.6.1.2.1.43.10.2.1.4.1.1  # Page count
#PrinterTestThreshold: 40  # Percentage of OIDs that need to return any response to consider it a printer
