debug: false
SuppressSnmpErrors: true
debug_date: false
debug_MM_YYYY: 9-2001
DateFilenameOffset: -5 #if x days before the 1st, date it for next month
subnets: #for findpriners.sh - subnets to search for priners in. will be used if debug is false.
  - 10.25.5.0/24 # brenham - servers 
  - 10.25.20.0/24 # Brenham - data vlan
  - 10.1.1.0/24
  - 10.1.2.0/24
  - 10.1.22.0/24
  - 10.17.25.0/24
  - 10.17.50.0/24
  - 10.2.2.0/24
  - 10.2.3.0/24
knownprinters: #typically for testing. wont be used if debug is off.  
  - 10.1.2.144
  - 10.1.2.145
  - 10.1.2.5
  - 10.25.5.54
  - 10.25.20.12
  - 10.25.5.254
  - 10.25.20.52
  - 10.25.5.68
  - 10.25.5.20
  - 10.25.5.21
  - 10.25.5.25
CPI_Printer_brands:
  - Epson
  - Konica Minolta
  - Ecosys
locations:
  - "10.25=Brenham"
  - "10.1=SulpherSprings"
multithreading: true #not possible right now
max_threads: 8 
PrinterTest: #not for the csv - what to test to see if it's a printer 
#  - .1.3.6.1.2.1.43.11.1.1.9.1  # Toner C
#  - .1.3.6.1.2.1.43.11.1.1.9.2  # Toner Y
  - .1.3.6.1.2.1.43.11.1.1.9.3  # Toner M
  - .1.3.6.1.2.1.43.11.1.1.9.4  # Toner K
  - .1.3.6.1.2.1.43.10.2.1.4.1.1  # Page count
PrinterTestThreshold: 40  # Percentage of OIDs that need to return any response to consider it a printer