services:
  mysql:
    build:
      context: .
      dockerfile: dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  python:
    build:
      context: .
      dockerfile: dockerfile.python
    volumes:
      - ./data/python:/app
    working_dir: /app
    command: ["python", "main.py"]

  apache:
    build:
      context: .
      dockerfile: dockerfile.apache
    ports:
      - "8080:80"
    volumes:
      - ./data/apache:/usr/local/apache2/htdocs/
      - ./src-web-interface:/usr/local/apache2/htdocs/web
    networks:
      - default

networks:
  default:
    driver: bridge
